### ISSUE TITLE
API Resource: General question

### ISSUE THREAD

**Issue by davixcky** [narnat/checker_api_hack_day#4]
Firstable, good job it's really helpful.

I've something to ask about the endpoints that Holberton offers and you are using.  Are just 5 endpoints? There is not more interaction with the holberton api?

Thanks in advance

**Comment by arthurdamm** [comment]
Hi David,

Thanks for your feedback, glad you like the Checker Buddy.

Correct, we only use 5 endpoints with the Holberton API. There is a 6th endpoint associated with this Hack Day Challenge (the reason these endpoints were exposed) providing info about the current user student profile, but we do not utilize it in this project.

Cheers!

**Comment by davixcky** [comment]
Thanks for your answer. 

I ask because I want to practice with the holberton api. So you are saying that holberton just have exposed 6 endpoints in total?

**Comment by arthurdamm** [comment]
For the Checker Hack Day API, yes.

This is the project page: https://intranet.hbtn.io/projects/434

If you do not have access to it you will need to check with Guillaume.

You can make your own attempts by studying the way we used to API and using
your API Key in the "Tools" section of your intranet profile if you are
trimester 3++.

Good luck!

**Comment by davixcky** [comment]
I already have a client for the rest API (the information that you have in the README was really helpful for me).

But I asked because I want for information. I think that I will build a scraper for that.

Thanks by the way :cheers:
